### ISSUE TITLE
Installing on macOS

### ISSUE THREAD

**Issue by wout** [miyako/console-rsvg-convert#1]
Hi,
What's the best way to install this on macOS?
I'm always getting the following error:

```
dyld: Library not loaded: @loader_path/libintl.8.dylib
```

**Comment by miyako** [comment]
thanks for reporting. I've added a copy of ``libiconv`` in https://github.com/miyako/console-rsvg-convert/releases/tag/1.0.1-mac does that solve your issue?

there is no installer, all the files are in the zip.

but the dynamic loader (``dyld``) searches standard paths such as ``usr/local/lib`` when it can't find a library, which is why I missed the dependency.

**Comment by wout** [comment]
Thanks for the quick reply and fix.
Now it works as expected.
